import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_componnents/puplicComponents/NavBar";
import Footer from "./_componnents/puplicComponents/Footer";
import Session_Provider from "./_utilites/providers/SessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Session_Provider>
        <div >
          <NavBar /> 
          {children}
          <Footer />
        </div>
        </Session_Provider>
      </body>
    </html>
  );
}
